server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: explorewithme
    password: explorewithme
    url: jdbc:postgresql://stats-postgres:5432/explorewithmestats

logging:
  level:
    root: info
    ru.practicum: info
