server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: explorewithme
    password: explorewithme
    url: jdbc:postgresql://main-postgres:5432/explorewithmemain
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    ru.practicum: info
