server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: jdbc:h2:mem:main_test_db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

logging:
  level:
    root: info
    ru.practicum: info
