server:
  port: ${MAIN_SERVER_PORTS}

spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: ${MAIN_SPRING_DATASOURCE_USERNAME}
    password: ${MAIN_SPRING_DATASOURCE_PASSWORD}
    url: jdbc:h2:mem:main_test_db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    ru.practicum: info
